Fix arch

diff --git a/recipes/appimageassistant/Recipe b/recipes/appimageassistant/Recipe
--- a/recipes/appimageassistant/Recipe
+++ b/recipes/appimageassistant/Recipe
@@ -13,6 +13,14 @@ if [ -z "$NO_DOWNLOAD" ] ; then
   sudo apt-get install -qq libfuse-dev libglib2.0-dev cmake libc6-dev binutils valac libgee-0.8-dev gcc-multilib g++-multilib libc6-dev-i386
 fi
 
+# Determine which architecture should be built
+if [[ "$(arch)" = "i686" || "$(arch)" = "x86_64" ]] ; then
+  ARCH=$(arch)
+  else
+    echo "Architecture could not be determined"
+    exit 1
+fi
+
 if [ ! -d AppImageKit ] ; then
   git clone https://github.com/probonopd/AppImageKit.git
 fi
