Include libcrypto cert.pem

diff --git a/recipes/hexchat/Recipe b/recipes/hexchat/Recipe
--- a/recipes/hexchat/Recipe
+++ b/recipes/hexchat/Recipe
@@ -96,15 +96,25 @@ find usr/ -type f -executable -exec sed -i -e "s|/usr|././|g" {} \;
 rm usr/lib/libgtk* usr/lib/libgdk* usr/lib/libpango* || true
 
 # Workaround for:
+#  Pango-CRITICAL **: pango_layout_get_line_count: assertion 'layout != NULL' failed
+# Floating point exception
+# TO BE WRITTEN
+
+# Workaround for:
 # On Ubuntu, "symbol lookup error: /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/liboverlay-scrollbar.so: undefined symbol: g_settings_new"
 rm usr/lib/libgio* || true
 
 # Workaround for:
 # "Connection failed (unable to get local issuer certificate.? (20))" on Ubuntu
-# TO BE DONE
+if [ -e usr/lib/libcrypto.so.10 ] ; then
+  echo "Copying in cert.pem"
+  sed -i -e 's|/etc/pki/tls/cert.pem|./et/pki/tls/cert.pem|g' usr/lib/libcrypto.so.10
+  mkdir -p usr/et/pki/tls/
+  cp /etc/pki/tls/cert.pem usr/et/pki/tls/
+fi
 
 # Unsure about these
-rm usr/lib/libgmodule* usr/lib/libatk* usr/lib/libcairo || true
+rm usr/lib/libgmodule* usr/lib/libatk* usr/lib/libcairo* usr/lib/libpixman* || true
 
 # Workaround for:
 # ./lib/libc.so.6: version `GLIBC_2.14' not found (required by /usr/lib64/libogg.so.0)
