Update Recipe

diff --git a/recipes/qtcreator/Recipe b/recipes/qtcreator/Recipe
--- a/recipes/qtcreator/Recipe
+++ b/recipes/qtcreator/Recipe
@@ -222,6 +222,8 @@ mv ./*/gcc_64/translations/qtwebengine_locales/en-US.pak ./*/gcc_64/translations
 rm ./*/gcc_64/translations/qtwebengine_locales/*
 mv  ./*/gcc_64/translations/en-US.pak ./*/gcc_64/translations/qtwebengine_locales/
 echo "The rest of the gcc_64/translations/qtwebengine_locales have been deleted to shrink the AppImage size; edit the recipe to change this." > MISSING_TRANSLATIONS.txt
+find . -name  *Qt3D* -exec rm -r {} \; || true
+echo "Qt3D been deleted to shrink the AppImage size; edit the recipe to change this." > MISSING_Qt3D.txt
 
 # Go out of AppImage
 cd ..
